# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\020FunkyChat.Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15protos/messages.proto\"\x99\x01\n\x07\x43ommand\x12\x1c\n\x04\x65\x63ho\x18\x01 \x01(\x0b\x32\x0c.EchoCommandH\x00\x12\x1c\n\x04\x63hat\x18\x02 \x01(\x0b\x32\x0c.ChatCommandH\x00\x12)\n\x0b\x64irect_chat\x18\x03 \x01(\x0b\x32\x12.DirectChatCommandH\x00\x12\x1c\n\x04\x65xit\x18\x04 \x01(\x0b\x32\x0c.ExitCommandH\x00\x42\t\n\x07\x63ommand\"\xb9\x01\n\x08Response\x12#\n\x07welcome\x18\x01 \x01(\x0b\x32\x10.WelcomeResponseH\x00\x12\x1d\n\x04\x65\x63ho\x18\x02 \x01(\x0b\x32\r.EchoResponseH\x00\x12\x1d\n\x04join\x18\x03 \x01(\x0b\x32\r.JoinResponseH\x00\x12\x1f\n\x05leave\x18\x04 \x01(\x0b\x32\x0e.LeaveResponseH\x00\x12\x1d\n\x04\x63hat\x18\x05 \x01(\x0b\x32\r.ChatResponseH\x00\x42\n\n\x08response\"\x1e\n\x0b\x45\x63hoCommand\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x43hatCommand\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x11\x44irectChatCommand\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\r\n\x0b\x45xitCommand\";\n\x0fWelcomeResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onnected_users\x18\x02 \x03(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\" \n\rLeaveResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"C\n\x0c\x43hatResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tis_direct\x18\x03 \x01(\x08\x42\x13\xaa\x02\x10\x46unkyChat.Protosb\x06proto3'
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo', full_name='Command.echo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chat', full_name='Command.chat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direct_chat', full_name='Command.direct_chat', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit', full_name='Command.exit', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='Command.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=179,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='welcome', full_name='Response.welcome', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='echo', full_name='Response.echo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='join', full_name='Response.join', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leave', full_name='Response.leave', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chat', full_name='Response.chat', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='Response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=182,
  serialized_end=367,
)


_ECHOCOMMAND = _descriptor.Descriptor(
  name='EchoCommand',
  full_name='EchoCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EchoCommand.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=399,
)


_CHATCOMMAND = _descriptor.Descriptor(
  name='ChatCommand',
  full_name='ChatCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ChatCommand.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=431,
)


_DIRECTCHATCOMMAND = _descriptor.Descriptor(
  name='DirectChatCommand',
  full_name='DirectChatCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='DirectChatCommand.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='DirectChatCommand.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=486,
)


_EXITCOMMAND = _descriptor.Descriptor(
  name='ExitCommand',
  full_name='ExitCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=501,
)


_WELCOMERESPONSE = _descriptor.Descriptor(
  name='WelcomeResponse',
  full_name='WelcomeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='WelcomeResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected_users', full_name='WelcomeResponse.connected_users', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=562,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EchoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=595,
)


_JOINRESPONSE = _descriptor.Descriptor(
  name='JoinResponse',
  full_name='JoinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='JoinResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=628,
)


_LEAVERESPONSE = _descriptor.Descriptor(
  name='LeaveResponse',
  full_name='LeaveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='LeaveResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=662,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ChatResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ChatResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_direct', full_name='ChatResponse.is_direct', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=731,
)

_COMMAND.fields_by_name['echo'].message_type = _ECHOCOMMAND
_COMMAND.fields_by_name['chat'].message_type = _CHATCOMMAND
_COMMAND.fields_by_name['direct_chat'].message_type = _DIRECTCHATCOMMAND
_COMMAND.fields_by_name['exit'].message_type = _EXITCOMMAND
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['echo'])
_COMMAND.fields_by_name['echo'].containing_oneof = _COMMAND.oneofs_by_name['command']
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['chat'])
_COMMAND.fields_by_name['chat'].containing_oneof = _COMMAND.oneofs_by_name['command']
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['direct_chat'])
_COMMAND.fields_by_name['direct_chat'].containing_oneof = _COMMAND.oneofs_by_name['command']
_COMMAND.oneofs_by_name['command'].fields.append(
  _COMMAND.fields_by_name['exit'])
_COMMAND.fields_by_name['exit'].containing_oneof = _COMMAND.oneofs_by_name['command']
_RESPONSE.fields_by_name['welcome'].message_type = _WELCOMERESPONSE
_RESPONSE.fields_by_name['echo'].message_type = _ECHORESPONSE
_RESPONSE.fields_by_name['join'].message_type = _JOINRESPONSE
_RESPONSE.fields_by_name['leave'].message_type = _LEAVERESPONSE
_RESPONSE.fields_by_name['chat'].message_type = _CHATRESPONSE
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['welcome'])
_RESPONSE.fields_by_name['welcome'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['echo'])
_RESPONSE.fields_by_name['echo'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['join'])
_RESPONSE.fields_by_name['join'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['leave'])
_RESPONSE.fields_by_name['leave'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['chat'])
_RESPONSE.fields_by_name['chat'].containing_oneof = _RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['EchoCommand'] = _ECHOCOMMAND
DESCRIPTOR.message_types_by_name['ChatCommand'] = _CHATCOMMAND
DESCRIPTOR.message_types_by_name['DirectChatCommand'] = _DIRECTCHATCOMMAND
DESCRIPTOR.message_types_by_name['ExitCommand'] = _EXITCOMMAND
DESCRIPTOR.message_types_by_name['WelcomeResponse'] = _WELCOMERESPONSE
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
DESCRIPTOR.message_types_by_name['JoinResponse'] = _JOINRESPONSE
DESCRIPTOR.message_types_by_name['LeaveResponse'] = _LEAVERESPONSE
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

EchoCommand = _reflection.GeneratedProtocolMessageType('EchoCommand', (_message.Message,), {
  'DESCRIPTOR' : _ECHOCOMMAND,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:EchoCommand)
  })
_sym_db.RegisterMessage(EchoCommand)

ChatCommand = _reflection.GeneratedProtocolMessageType('ChatCommand', (_message.Message,), {
  'DESCRIPTOR' : _CHATCOMMAND,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:ChatCommand)
  })
_sym_db.RegisterMessage(ChatCommand)

DirectChatCommand = _reflection.GeneratedProtocolMessageType('DirectChatCommand', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTCHATCOMMAND,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:DirectChatCommand)
  })
_sym_db.RegisterMessage(DirectChatCommand)

ExitCommand = _reflection.GeneratedProtocolMessageType('ExitCommand', (_message.Message,), {
  'DESCRIPTOR' : _EXITCOMMAND,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:ExitCommand)
  })
_sym_db.RegisterMessage(ExitCommand)

WelcomeResponse = _reflection.GeneratedProtocolMessageType('WelcomeResponse', (_message.Message,), {
  'DESCRIPTOR' : _WELCOMERESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:WelcomeResponse)
  })
_sym_db.RegisterMessage(WelcomeResponse)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

JoinResponse = _reflection.GeneratedProtocolMessageType('JoinResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOINRESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:JoinResponse)
  })
_sym_db.RegisterMessage(JoinResponse)

LeaveResponse = _reflection.GeneratedProtocolMessageType('LeaveResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEAVERESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:LeaveResponse)
  })
_sym_db.RegisterMessage(LeaveResponse)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPONSE,
  '__module__' : 'protos.messages_pb2'
  # @@protoc_insertion_point(class_scope:ChatResponse)
  })
_sym_db.RegisterMessage(ChatResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
