name: Release

on:
  release:
    types: [published]

jobs:
  server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: ./src/Server
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Zip build
      uses: papeloto/action-zip@v1
      with:
        files: src/Server/bin/Release/net5.0/
        dest: "funky-chat-server-${{ runner.os }}.zip"
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: "**/funky-chat-server-${{ runner.os }}.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  rust-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
